FusionAI/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500
from applications.home.views import Error404View, Error500View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.users.urls')),
    path('',include('applications.post.urls')),
    path('',include('applications.favorites.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = Error404View.as_view()
handler500= Error500View.as_error_view()

applications/home/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('add-subscription',views.SubcriberCreateView.as_view(), name='add_subscription'),
    path('message-contact',views.ContactCreateView.as_view(), name='message_contact')
]

applications/post/urls.py
from django.urls import path
from . import views

app_name = 'post_app'

urlpatterns = [
    path('post-list/',views.ArticleList.as_view(),name='list'),
    path('post-detail/<slug>/',views.ArticleDetailView.as_view(),name='detail')
]

applications/home/models.py
from django.db import models
# Third_party app
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    title = models.CharField(max_length=70, verbose_name='title')
    description = models.TextField(verbose_name='description')
    about_title = models.CharField(max_length=70, verbose_name='about title')
    about_text = models.TextField(verbose_name='about description')
    contact_email = models.EmailField(blank=True, null=True, verbose_name='email')
    subject_email = models.CharField(max_length=50, blank=True, null=True, verbose_name='email subject')
    body_email = models.CharField(max_length=100, blank=True, null=True, verbose_name='email body')
    web = models.CharField(max_length=50, blank=True, null=True, verbose_name='web')
    repository = models.CharField(max_length=100, blank=True, null=True, verbose_name='repository')
    phone = models.CharField(blank=True, null=True, max_length=20, verbose_name='phone')


    class Meta:
        verbose_name = 'homepage'
        verbose_name_plural ='main pages'
    
    def __str__(self):
        return self.title


class Subscriber(TimeStampedModel):
    email = models.EmailField(verbose_name='email')

    class Meta:
        verbose_name='subscriber'
        verbose_name_plural='subscribers'
    
    def __str__(self):
        return self.email


class Contact(TimeStampedModel):
    full_name = models.CharField(max_length=100, verbose_name='name')
    email = models.EmailField(verbose_name='email')
    message = models.TextField(verbose_name='message')

    class Meta:
        verbose_name='contact'
        verbose_name_plural='contacts'
    
    def __str__(self):
        return self.full_name

applications/home/forms.py
from django import forms
from .models import Subscriber, Contact

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = [
            'email',
        ]
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder':'Correo',
                    'class': 'form-control'
                }     
            )   
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('__all__')

applications/home/views.py
import json
import os

from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from applications.post.models import Article

from .models import Home, Subscriber, Contact
from .forms import SubscriberForm, ContactForm

#email direction
with open("secret.json") as f:
    secret = json.loads(f.read())

def get_secret(secret_name, secrets=secret):
    try:
        return secrets[secret_name]
    except:
        msg = "The variable %s does not exist" % secret_name
        raise ImproperlyConfigured(msg)


class Error404View(generic.TemplateView):
    template_name = 'home/404.html'

class Error500View(generic.TemplateView):
    template_name = 'home/500.html'

    @classmethod
    def as_error_view(cls):
        v = cls.as_view()
        def view(request):
            r = v(request)
            r.render()
            return r
        return view


class HomePage(generic.TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        try:
            context = super(HomePage, self).get_context_data(**kwargs)
            context["home"] = Home.objects.latest('created')
            context["cover_page"] = Article.objects.cover_page()
            context["articles"] = Article.objects.articles_on_home()
            context["last_articles"] = Article.objects.last_articles_on_home()

            #formSubscriptions
            context["form"] = SubscriberForm
            
        except:
            print('Enter data from the admin to view content')
            context["empty"] = "Nothing to see"
        
        return context
    
    
class SubcriberCreateView(SuccessMessageMixin, generic.CreateView):

    form_class = SubscriberForm
    success_message = "Gracias por suscribirte 😊"
    error_message = "Disculpa, algo salió mal. Inténtalo de nuevo 👀"
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super(SubcriberCreateView, self).get_context_data(**kwargs)

        return context

    def form_valid(self, form):
        subs = Subscriber.objects.get_or_create(
            email = form.cleaned_data['email']
        )
        messages.success(self.request, self.success_message)

         #send email 
        try:
            to_email = form.cleaned_data['email']

            subject = 'Gracias por suscribirte'
            message = f'Tu suscripción ha sido confirmada. \n\n FusionAI.'
            from_email = get_secret('EMAIL_USER')
            send_mail(subject, message, from_email, [to_email])
        except (RuntimeError, TypeError, NameError):
            pass

        return HttpResponseRedirect(reverse('home_app:index'))
    
    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        
        return HttpResponseRedirect(reverse('home_app:index'))

    
class ContactCreateView(SuccessMessageMixin, generic.CreateView):
    form_class = ContactForm
    success_message = "Gracias por ponerte en contacto 😊"
    error_message = "Disculpa, algo salió mal. Inténtalo de nuevo 👀"
    template_name = 'includes/contact.html'

    def get_context_data(self, **kwargs):
        context = super(ContactCreateView, self).get_context_data(**kwargs)

        return context
    
    def form_valid(self, form):
        subs = Contact.objects.get_or_create(
            full_name = form.cleaned_data['full_name'],
            email = form.cleaned_data['email'],
            message = form.cleaned_data['message']
        )
        
        messages.success(self.request, self.success_message)
        
        #send email 
        try:
            name = form.cleaned_data['full_name']
            to_email = form.cleaned_data['email']

            subject = 'Gracias por ponerte en contacto'
            message = f'Hola {name}, gracias por enviarnos un mensaje. Te responderemos lo más pronto posible. \n\n FusionAI.'
            from_email = get_secret('EMAIL_USER')
            send_mail(subject, message, from_email, [to_email])
        except (RuntimeError, TypeError, NameError):
            pass

        return HttpResponseRedirect(reverse('home_app:index'))

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        
        return HttpResponseRedirect(reverse('home_app:index'))

templates/home/base_home.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

templates/base.html

templates/home/index.html
{% extends 'home/base_home.html' %}

{% load static %}

{% block title %}Inicio{% endblock title%}
{% block description %}{{home.description}}{% endblock description%}

{% block content %}

{% include 'includes/header.html' %}

<div class="container">
  <div class='row'>
    <div class='col-12 col-md-6 offset-md-3 text-center p-2'>
        {% if messages %}
            {% for message in messages %}
                <div class="message-{{message.tags}} alert border-2 border-{{message.tags}}" role="alert">
                    {{message}}
                </div>
            {% endfor %}    
        {% endif %}
    </div>
  </div>  

  <div class="row mb-2">

    <div class="col-12 col-md-10 offset-md-1">
      <div class="card h-100 text-center">
        <h1 class="card-header">{{ home.title }}</h1>
        <img src="{% static '/img/AI.svg' %}" class="card-img-top img-fluid" alt="FusionAI Logo">
        <div class="card-body">
          <h5 class="card-title text-center">{{ home.description }}</h5>
          <p class="card-text"><small>{{home.about_text}}</small></p>
        </div>
        
        <div class="card-footer">
          <button type="button" class="btn border border-white border-3 text-white" data-bs-toggle="modal" data-bs-target="#subscribeModal">
            Suscribirme
          </button>
          <!-- Modal -->
          <div class="modal fade" id="subscribeModal" tabindex="-1" aria-labelledby="subscribeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="subscribeModalLabel">Suscribirme a FusionAI</h5>
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'home_app:add_subscription' %}">
                  <div class="modal-body">
                    {% csrf_token %}
                    {{form.email}}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn border border-secondary border-2 text-white" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn border border-primary border-2 text-white">Suscribirme</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>  

    {% if cover_page %}
    <div class="col-12 col-md-10 mt-4 offset-md-1">
      <div class="card h-100">
        <div class="row align-items-center g-0">
          <div class="col-md-4">
            <img src="{% static '/img/WhatIsAI.png' %}" class="img-card img-home img-fluid" alt="{{ cover_page.title }}">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <p class="card-text">{{ cover_page.content|safe|truncatewords:37 }}</p>
            </div>
          </div>
          <div class="card-footer text-center">
            <a href="{% url 'post_app:detail' cover_page.slug %}" class="btn border border-primary border-2 text-white">Ver más</a>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    
  </div>  
  
  <div class="essentials alert m-5" role="alert">
    &#10024; Los esenciales &#10024;
  </div>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for i in articles %}
      <div class="col">
        <div class="card h-100">
          <img src="{{ i.image.url }}" class="img-card card-img-top" alt="{{ i.title }}">
          <div class="card-body">
            <h5 class="card-title text-center">{{ i.title|truncatechars:100 }}</h5>
            <p class="card-text">{{ i.content|safe|truncatewords_html:30|striptags }}</p>
          </div>
          <div class="card-footer text-center">
            <a href="{% url 'post_app:detail' i.slug %}" class="btn border border-primary border-2 text-white">Ver más</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="recents alert m-5" role="alert">
    &#128293; Los más recientes &#128293;
  </div>
    
  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for article in last_articles %}
      <div class="col">
        <div class="card h-100">
          <img src="{{ article.image.url }}" class="img-card card-img-top" alt="{{ article.title }}">
          <div class="card-body">
            <h5 class="card-title text-center">{{ article.title|truncatechars:100 }}</h5>
            <p class="card-text">{{ article.content|safe|truncatewords_html:30|striptags }}</p>
          </div>
          <div class="card-footer text-center">
            <a href="{% url 'post_app:detail' article.slug %}" class="btn border border-primary border-2 text-white">Ver más</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% include 'includes/contact.html' %}
{% include 'includes/footer.html' %}


{% endblock content %}