FusionAI/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500
from applications.home.views import Error404View, Error500View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.users.urls')),
    path('',include('applications.post.urls')),
    path('',include('applications.favorites.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = Error404View.as_view()
handler500= Error500View.as_error_view()

applications/favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites_app'

urlpatterns = [
    path('favorites/', views.FavoriteItemsListView.as_view(), name='favoriteItems'),
    path('favorites-add/<int:pk>/', views.FavoriteAddItems.as_view(), name='favoriteAdd'),
    path('favorites-remove/<int:pk>/',views.FavoriteRemoveDeleteView.as_view(), name='favoriteRemove')
]

applications/home/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('add-subscription',views.SubcriberCreateView.as_view(), name='add_subscription'),
    path('message-contact',views.ContactCreateView.as_view(), name='message_contact')
]

applications/post/urls.py
from django.urls import path
from . import views

app_name = 'post_app'

urlpatterns = [
    path('post-list/',views.ArticleList.as_view(),name='list'),
    path('post-detail/<slug>/',views.ArticleDetailView.as_view(),name='detail')
]

applications/users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('user-register/', views.UserRegister.as_view(), name='userRegister'),
    path('user-login/', views.UserLogin.as_view(), name='userLogin'),
    path('user-logout/', views.UserLogout.as_view(), name='userLogout'),
    path('user-password-update/', views.UserPasswordUpdate.as_view(), name='userPasswordUpdate'),
    path('user-verification/<pk>/', views.UserVerification.as_view(), name='userVerification'),
    path('user-profile', views.UserProfile.as_view(), name='userProfile')
]

templates/includes/contact.html
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <div class="card">
                <h5 class="card-header" id="contact">Contacto</h5>
                <div class="card-body">
                    <form class="form-control" method="POST" action="{% url 'home_app:message_contact' %}">
                        {% csrf_token %}
                        <div class="row g-2 mb-3">
                            <div class="col-sm-6">
                                <input type="text" name="full_name" placeholder="Nombre" class="form-control" maxlength="100" required="" id="id_full_name">
                            </div>
                            <div class="col-sm">
                                <input type="email" name="email" placeholder="Correo" class="form-control" maxlength="254" required="" id="id_email">
                            </div>
                        </div>
                        <textarea class="form-control mb-3" name= "message" id="id_message" rows="3" placeholder="Mensaje"></textarea>
                        <button type="submit" class="btn border border-2 border-success text-white">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/includes/footer.html
<footer class="text-center text-lg-start text-muted mt-4">
    <section class="d-flex justify-content-center p-2 border-bottom">
        <h6 class="text-reset">
            {{title}}<span class="me-5 d-none d-lg-inline">: {{description}}</span>
        </h6>
    </section>

    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <div class="container text-center text-md-start mt-5">
            <div class="row mt-3">
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto">
                    <h6 class="mb-4">FusionAI</h6>
                    <p>
                        {{about_text}}
                    </p>
                </div>
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <h6 class="text-uppercase mb-4">
                        Realizado con
                    </h6>
                    <p>
                        <a href="https://www.djangoproject.com" class="text-reset" target="__blank">Django</a>
                    </p>
                    <p>
                        <a href="https://getbootstrap.com/" class="text-reset" target="__blank">Bootstrap</a>
                    </p>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <h6 class="text-uppercase mb-4">
                        Repositorio
                    </h6>
                    <p>
                        <a href="{{repository}}" class="text-reset" target="__blank">GitHub</a>
                    </p>
                </div>
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <h6 class="text-uppercase mb-4">
                        Más contacto
                    </h6>
                    <p>
                        <a class="text-reset" href="mailto:{{contact_email}}?subject={{subject_email}}&body={{body_email}}">Correo</a>  
                    </p>
                    <p>
                        <a class="text-reset" href="{{web}}" target="__blank">Web</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <div class="text-center p-2">
        Copyleft <span id="copyleft">&copy;</span> 
        Desarrollado por <a class="text-reset website" href="https://diegovasconcelo.com/" target="__blank">DVU</a>
    </div>
</footer>

templates/includes/header.html
{%load static %}
<header>
  <nav class="navbar sticky-top navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home_app:index' %}">
          <img src="{% static '/img/FAI_icon.png' %}" class="logo d-inline-block align-top" alt="FusionAI Brand">
          FusionAI
        </a>
        <span class="d-flex">
          <button id="switch" class="btn-mode" onclick="changeMode()">
            <span class="dark-moon">🌙</span>
            <span class="light-fusion">☀️</span>
          </button>
        </span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"><span id="toggler-icon">|||</span></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" aria-current="page" href="{% url 'home_app:index' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'list' %}active{% endif %}" href="{% url 'post_app:list' %}">Posts</a>
            </li>
            {% if user.id %}
              <li class="nav-item dropdown">
                <a class="nav-link {% if request.resolver_match.url_name == 'favoriteItems' or request.resolver_match.url_name == 'userProfile' %}active{% endif %} dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hola, {{user.names}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item {% if request.resolver_match.url_name == 'favoriteItems' %}active{% endif %} text-center" href="{% url 'favorites_app:favoriteItems' %}">Favoritos</a></li>
                  <li><a class="dropdown-item {% if request.resolver_match.url_name == 'userProfile' %}active{% endif %} text-center" href="{% url 'users_app:userProfile' %}">Perfil</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item text-center" href="{% url 'users_app:userLogout' %}">Cerrar sesión</a></li>
                </ul>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'userLogin' %}active{% endif %}" href="{% url 'users_app:userLogin' %}">Iniciar sesión</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'userRegister' %}active{% endif %}" href="{% url 'users_app:userRegister' %}">Registrarse</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
  </nav>
</header>