FusionAI/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404, handler500
from applications.home.views import Error404View, Error500View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.users.urls')),
    path('',include('applications.post.urls')),
    path('',include('applications.favorites.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = Error404View.as_view()
handler500= Error500View.as_error_view()

applications/favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites_app'

urlpatterns = [
    path('favorites/', views.FavoriteItemsListView.as_view(), name='favoriteItems'),
    path('favorites-add/<int:pk>/', views.FavoriteAddItems.as_view(), name='favoriteAdd'),
    path('favorites-remove/<int:pk>/',views.FavoriteRemoveDeleteView.as_view(), name='favoriteRemove')
]

applications/post/urls.py
from django.urls import path
from . import views

app_name = 'post_app'

urlpatterns = [
    path('post-list/',views.ArticleList.as_view(),name='list'),
    path('post-detail/<slug>/',views.ArticleDetailView.as_view(),name='detail')
]

applications/post/models.py
from datetime import timedelta, datetime

from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
# Third_party app
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

from .managers import PostManager



class Category(TimeStampedModel):
    name = models.CharField(max_length=30, unique=True, verbose_name='name')
    description = models.CharField(max_length=200, unique=True, verbose_name='description')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Tag(TimeStampedModel):
    tag = models.CharField(max_length=50, verbose_name='Tag')
    
    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'

    def __str__(self):
        return self.tag

class Article(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='user')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='category') 
    tag = models.ManyToManyField("post.Tag", verbose_name='tags')
    title = models.CharField(max_length=200, verbose_name='title')
    content = RichTextUploadingField(verbose_name='content')
    public = models.BooleanField(default=False, verbose_name='public?')
    image = models.ImageField(upload_to='entry',verbose_name='image')
    cover_page = models.BooleanField(default=False, verbose_name='cover page?')
    in_home = models.BooleanField(default=False, verbose_name='On the home page?')
    slug = models.SlugField(editable=False, max_length=200)

    objects = PostManager()


    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        #Generate unic slug
        now = datetime.now()
        total_time = timedelta(hours=now.hour, minutes=now.minute, seconds=now.second)
        seconds = int(total_time.total_seconds())

        slug_unique = '%s %s' % (self.title, str(seconds))
        self.slug = slugify(slug_unique)

        super(Article, self).save(*args, **kwargs)

applications/post/views.py
from django.shortcuts import render
from django.views import generic
from .models import Category, Article
from applications.favorites.models import Favorite

class ArticleList(generic.ListView):
    template_name = 'post/list.html'
    context_object_name = 'posts'
    paginate_by = 4

    
    def get_context_data(self, **kwargs):
        context = super(ArticleList, self).get_context_data(**kwargs)
        context['categories']= Category.objects.all()
        
        parameters = self.request.GET.copy()
        if parameters.get('page') != None:
            del parameters['page']
        context['parameters'] = parameters
        
        return context

    def get_queryset(self):
        kw = self.request.GET.get('kword','')
        category = self.request.GET.get('category','')

        result = Article.objects.search_article(kw, category)

        return result

class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = 'post/detail.html'
    
    def get_context_data(self, **kwargs):
        try:
            context = super(ArticleDetailView, self).get_context_data(**kwargs)
            user = self.request.user
            article = self.kwargs['slug']
            context['favorite'] = Favorite.objects.is_favorite(user, article)
        except:
            context['error'] = "Disculpa, algo salió mal."
        
        return context

templates/post/base_post.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

templates/post/detail.html
{% extends 'post/base_post.html'%}

{% load static %}

{% block title %}Post: {{article.title}}{% endblock title %}

{% block content %}

    {% include 'includes/header.html' %}

    <div id="content" class="container">
        <div class="row">
            <h1 class="text-center mb-4">{{article.title}}</h1>
            {% if error %}
                <div class='col-12 col-md-6 offset-md-3 text-center p-2'>
                    <div class="message-danger alert border-2 border-danger" role="alert">
                        {{error}}
                    </div>
                </div>
            {% endif %}


            <div class="col-12 mb-2">
                {%if favorite %}
                    {% for data in favorite %}
                        <form method="POST" action="{% url 'favorites_app:favoriteRemove' data.id %}">
                            {% csrf_token %}
                            <div class="d-grid gap-2 d-md-block text-center">
                                <button class="btn border border-white me-md-2 text-white" type="submit">Remover de favoritos &#128420;</button>
                                <a href="javascript:getlink();" id="linkCopy" class="btn border border-white text-white">Copy link &#128279;</a>
                            </div>
                        </form>
                    {% endfor %}
                {% else %}
                <form method="POST" action="{% url 'favorites_app:favoriteAdd' article.id %}">
                    {% csrf_token %}
                    <div class="d-grid gap-2 d-md-block text-center">
                        <button class="btn border border-white me-md-2 text-white" type="submit">Agregar a favoritos &#128420;</button>
                        <a href="javascript:getlink();" id="linkCopy" class="btn border border-white text-white">Copiar link &#128279;</a>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card h-100"> 
                    <div class="card-body">
                        <p class="card-text text-muted">{{article.content|safe}}</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% include 'includes/footer.html' %}

{% endblock content %}

templates/post/list.html
{% extends 'post/base_post.html'%}

{% load static %}

{% block title %}Posts {{article.title}}{% endblock title %}

{% block content %}

    {% include 'includes/header.html' %}

    <div class="container" id="content">
        <h1>Posts</h1>            
        <div class="row">
            <div class="col-12 col-sm-12 col-lg-8 mb-2">
                <form class="form-control d-flex" method="GET">
                    <input class="form-control me-2" type="text" name="kword" placeholder="Buscar por palabras clave (título)" aria-label="Search">
                    <button class="btn border border-2 text-white" type="submit">Buscar</button>
                </form>
            </div>
        </div>

        <div class="row">

            <div class="col-12 col-sm-12 col-lg-4 d-lg-none">

                <div class="card mb-4">
                    <div class="card-body">

                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        <h5 class="card-title">Categorías</h5>
                                    </button>
                                </h2>

                                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne">
                                    <div class="accordion-body">
                                        <a href="{% url 'post_app:list'%}">Todas</a>
                                    </div>
                                </div>

                              {% for category in categories %}
                                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne">
                                    <div class="accordion-body">
                                        <a href="?category={{category.name}}">{{category.name}}</a>
                                    </div>
                                </div>
                                {%endfor%}
                            </div>
                        </div>

                    </div>
                </div>
                

            </div>

            <div class="col-12 col-sm-12 col-lg-8">
                
                <div class="row row-cols-1 row-cols-md-2 g-4">
                    {% for post in posts %}
                        <div class="col">
                            <div class="card h-100">
                                <div class="overflow">
                                    <img src="{{post.image.url}}" class="img-card card-img-top" alt="{{post.title}}">
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title text-center">{{post.title}}</h5>    
                                    <a href="?category={{post.category}}" class="text-category btn border border-1 text-white">
                                        {{post.category}}
                                    </a>
                                    <ul class="list-group list-group-horizontal">
                                        {% for t in post.tag.all %}
                                            <li class="tags list-group-item">{{t.tag|truncatechars:17}}</li>
                                        {%endfor%}
                                    </ul>
                                    <p class="card-text">{{post.content|truncatewords_html:20|safe|striptags}}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'post_app:detail' post.slug %}" class="btn border border-primary border-2 text-white">Ver más</a>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-md-6 offset-md-3">
                            <div class="card h-100">
                                <img src="{% static '/img/addFav.svg' %}" class="card-img-top" alt="img: Add items">
                                <div class="card-body">
                                    <h5 class="card-title">Nada para ver</h5>
                                    <p class="card-text"><a href="{% url 'post_app:list'%}">Haz clic aquí</a> para ver todos los posts.</p>
                                </div>
                            </div>
                        </div>
                    {% endfor%}
                </div>                

            </div>
        
            <div class="col-12 col-sm-12 col-lg-4 d-none d-lg-block">
                <div class="card">
                    <div class="card-body">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        <h5 class="card-title">Categorias</h5>
                                    </button>
                                </h2>

                                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne">
                                    <div class="accordion-body">
                                        <a href="{% url 'post_app:list'%}">Todas</a>
                                    </div>
                                </div>

                              {% for category in categories %}
                                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne">
                                    <div class="accordion-body">
                                        <a href="?category={{category.name}}">{{category.name}}</a>
                                    </div>
                                </div>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- paginator -->
        {% if is_paginated %}
        <div class="row pt-4">
            <div class='col-12 col-lg-4 offset-lg-2'>
                <nav aria-label="pagination">
                    <ul class="pagination pagination-sm justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="pagination page-link border border-light" href="?page=1 {% if parameters.urlencode %}&{{ parameters.urlencode }}{% endif %}" tabindex="-1">&laquo;</a>
                            </li>
                            <li class="page-item">
                                <a class="pagination page-link border border-light" href="?page={{page_obj.previous_page_number}}{% if parameters.urlencode %}&{{ parameters.urlencode }}{% endif %}" tabindex="-1">Anterior</a>
                            </li>
                        {% elif page_obj.number == 1  %}
                            <li class="page-item disabled">
                                <a class="pagination page-link border border-light" href="" tabindex="-1">&laquo;</a>
                            </li>
                            <li class="page-item disabled">
                                <a class="pagination page-link border border-light" href="" tabindex="-1">Anterior</a>
                            </li>
                        {%endif%}
        
                        <li class="page-item active">
                            <a class="pagination page-link border border-light">{{page_obj.number}} de {{page_obj.paginator.num_pages}}<span class="sr-only"></span></a>
                        </li>
        
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="pagination page-link border border-light" href='?page={{page_obj.next_page_number}}{% if parameters.urlencode %}&{{ parameters.urlencode }}{% endif %}'>Siguiente</a>
                            </li>
                            <li class="page-item">
                                <a class="pagination page-link border border-light" href='?page={{page_obj.paginator.num_pages}}{% if parameters.urlencode %}&{{ parameters.urlencode }}{% endif %}'>&raquo;</a>
                            </li>
                        {% elif not page_obj.has_next %}
                            <li class="page-item disabled">
                                <a class="pagination page-link border border-light" href=''>Siguiente</a>
                            </li>
                            <li class="page-item disabled">
                                <a class="pagination page-link border border-light" href=''>&raquo;</a>
                            </li>
                        {%endif%}
                    </ul>
                </nav>
            </div>
        </div>
        {% endif %}
    </div>
    
    

    {% include 'includes/footer.html' %}

{% endblock content %}